info:
  version: 1.0.0
  title: Product_Alicorp_Sample_002
  name: product-alicorp-sample-002
gateways:
  - datapower-api-gateway
plans:
  default-plan:
    title: Default Plan
    description: Default Plan
    rate-limits:
      default:
        value: 2/1minute
        hard-limit: true
  nuevo-plan:
    title: NUEVO PLAN
    rate-limits:
      new memberships:
        value: 10/1minute
        hard-limit: false
    burst-limits:
      Default burst-limit:
        value: 10/1second
  otro:
    title: OTRO
    rate-limits:
      Default rate-limit:
        value: 100/1hour
        hard-limit: false
apis:
  api-alicorp-sample-0011.0.0:
    $ref: .\api-alicorp-sample-001_1.0.0.yaml
visibility:
  view:
    type: public
    orgs: []
    tags: []
    enabled: true
  subscribe:
    type: authenticated
    orgs: []
    tags: []
    enabled: true
product: 1.0.0
